# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
#
# NOTE: This workflow is overkill for most R packages and
# check-standard.yaml is likely a better choice.
# usethis::use_github_action("check-standard") will install it.
on:
  push:
  pull_request:

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-11,   r: 'release'}
          - {os: macOS-11,   r: 'release'}
          - {os: macOS-11,   r: 'release'}
          - {os: macOS-11,   r: 'release'}
          - {os: macOS-11,   r: 'release'}
          - {os: macOS-12,   r: 'release'}
          - {os: macOS-12,   r: 'release'}
          - {os: macOS-12,   r: 'release'}
          - {os: macOS-12,   r: 'release'}
          - {os: macOS-12,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Cleanup
        run: rm -Rfv ~/Library/Logs/DiagnosticReports/*

      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        env:
          CURL_SSL_BACKEND: ${{ matrix.config.ssl-backend }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: crashreport
          path: ~/Library/Logs/DiagnosticReports/
